fix OSError due to http path
File "C:\Users\18000\anaconda3\lib\shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc:
OSError: [Errno 22] Invalid argument: 'C:\\Users\\18000\\Desktop\\ObsidianCorningSpace\\journals\\http:\\mmbiz.qpic.cn\\mmbiz\\17MiccsGRV0D2LfqIJGaG0SdOrQ3Ebl0BZmSDrMLia8x0UgcCzQDzkNrSuo7FfOQUkMbYHVvNYDtbv4YicqvaQl6w\\640?wx_fmt=png'